FEEDS = {
    "nigeria": {
        "Sahara Reporters": "https://saharareporters.com/feeds/latest/feed",
        "Sahara Reporters (Google)": "https://news.google.com/rss/search?q=site:saharareporters.com&hl=en-NG&gl=NG&ceid=NG:en",
        "Daily Trust": "https://dailytrust.com/feed/",
        "Daily Trust (Google)": "https://news.google.com/rss/search?q=site:dailytrust.com&hl=en-NG&gl=NG&ceid=NG:en",
        "Linda Ikeji": "https://www.lindaikejisblog.com/feeds/posts/default?alt=rss",
        "Linda Ikeji (Google)": "https://news.google.com/rss/search?q=site:lindaikejisblog.com&hl=en-NG&gl=NG&ceid=NG:en",
        "Premium Times": "https://www.premiumtimesng.com/feed",
        "Premium Times (Google)": "https://news.google.com/rss/search?q=site:premiumtimesng.com&hl=en-NG&gl=NG&ceid=NG:en",
        "Punch": "https://punchng.com/feed/",
        "Punch (Google)": "https://news.google.com/rss/search?q=site:punchng.com&hl=en-NG&gl=NG&ceid=NG:en",
        "Vanguard": "https://www.vanguardngr.com/feed/",
        "Guardian NG": "https://guardian.ng/feed/",
        "Channels": "https://www.channelstv.com/feed/",
        "TheCable": "https://www.thecable.ng/feed",
        "BusinessDay": "https://businessday.ng/feed/",
        "Leadership": "https://leadership.ng/feed/",
        "Tribune": "https://tribuneonlineng.com/feed/",
        "PM News": "https://pmnewsnigeria.com/feed/",
        "Daily Post": "https://dailypost.ng/feed/",
        "ICIR": "https://www.icirnigeria.org/feed/",
        "HumAngle": "https://humanglemedia.com/feed/",
    },
    "africa": {
        "AllAfrica": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
        "BBC Africa": "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
    },
    "world": {
        "Reuters": "https://feeds.reuters.com/reuters/worldNews",
        "Reuters (Google)": "https://news.google.com/rss/search?q=site:reuters.com+world&hl=en&gl=US&ceid=US:en",
        "Al Jazeera": "https://www.aljazeera.com/xml/rss/all.xml",
    },
}
